### ISSUE TITLE
Issue in username argument

### ISSUE THREAD

**Issue by grace-spec** [wjrl/RBioFabric#2]
Followed this code `install_github('RBioFabric',  username='wjrl')`  but faced the below issue. Is there any way this can be addressed? 

==

Error in parse_repo_spec(repo) : Invalid git repo specification: 'RBioFabric'
1 components of `...` were not used.

We detected these problematic arguments:
* `username`

Did you misspecify an argument?

**Comment by wjrl** [comment]
Looks like install_github() has changed in the many years since the example was created. See: https://github.com/skardhamar/rga/issues/99#issuecomment-455585240. Does using install_github('wjrl/RBioFabric') work for you?

**Comment by grace-spec** [comment]
Yes this now works! Thanks very much.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
